### ISSUE TITLE
amba模型运行

### ISSUE THREAD

**Issue by alien-kai** [Shanshan7/easy_perception#21]
报错：
···
CAVALRY_RUN_DAGS: Operation not permitted
[LIBNN  ERR] CAVALRY_RUN_DAGS MSG_RVAL: 0x0
Net_id: 0, Dags: 0 / 9, vp_ticks: 0, vp_time: 0 us, arm_time: 14811 us
nnctrl_run_net failed at iteration [0], ret: -1
nnctrl_run_net err
serial run one net idx: 0 err
start all nets err
···

**Comment by alien-kai** [comment]
解决方案：
···
modprobe cavalry && /usr/local/bin/cavalry_load -f /lib/firmware/cavalry.bin -r #
···
然后运行代码

**Comment by foww-0001** [comment]
问题已解决。
